Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2022-11, with the labels that each got.

#14 SUL23-43 Style the basic page card and list items
  .eslintrc.json
  .gitignore
  components/layouts/main-content-layout.tsx
  components/layouts/one-column.tsx
  components/layouts/page-layout.tsx
  components/nodes/node-stanford-page.tsx
  components/paragraphs/stanford-banner.tsx
  components/paragraphs/stanford-card.tsx
  components/paragraphs/stanford-entity.tsx
  components/paragraphs/stanford-image-gallery.tsx
  components/paragraphs/stanford-lists.tsx
  components/paragraphs/stanford-media-caption.tsx
  components/patterns/card.tsx
  components/simple/image.tsx
  components/simple/link.tsx
  lib/clean-node.tsx
  lib/drupal.ts
  lib/fetch-paragraphs.tsx
  next-seo.config.tsx
  package.json
  pages/[...slug].tsx
  pages/_app.tsx
  pages/api/node/[...slug].tsx
  pages/api/views/[...slug].tsx
  pages/index.tsx
  types/drupal.d.ts
  yarn.lock
Labels: size/m

#16 paragraph preview
  pages/admin/paragraph/[id].tsx
Labels: size/xs

#23 Better Oembed Handling for paragraphs and wysiwyg
  components/layouts/main-content-layout.tsx
  components/menu/main-menu.tsx
  components/nodes/node-stanford-news.tsx
  components/paragraphs/stanford-card.tsx
  components/paragraphs/stanford-media-caption.tsx
  components/paragraphs/stanford-wysiwyg.tsx
  components/simple/oembed.tsx
  lib/format-html.tsx
  lib/menu.tsx
  lib/use-on-screen.tsx
  pages/404.tsx
  pages/[...slug].tsx
  pages/_app.tsx
  pages/api/menu.tsx
  pages/index.tsx
  styles/globals.css
Labels: size/s

#24 SUL23-40 | @jdwjdwjdw | Add styles for News nodes, lists, and cards
  components/nodes/node-stanford-news.tsx
  components/patterns/card.tsx
  components/simple/icons/FacebookIcon.tsx
  components/simple/icons/LinkedInIcon.tsx
  components/simple/icons/TwitterIcon.tsx
  styles/globals.css
Labels: size/s

#30 SUL23-60 Style the header and footer components
  components/header.tsx
  components/layouts/main-content-layout.tsx
  components/layouts/page-layout.tsx
  components/menu/main-menu.tsx
  components/menu/side-nav.tsx
  components/nodes/node-stanford-news.tsx
  components/nodes/node-stanford-page.tsx
  components/patterns/banner.tsx
  components/patterns/card.tsx
  components/patterns/identity-bar.tsx
  components/patterns/lockup.tsx
  components/search/search-works.tsx
  components/simple/conditional.tsx
  components/simple/logo.tsx
  components/simple/outside-click-handler.tsx
  context/state.tsx
  lib/build-menu-tree.tsx
  lib/menu.tsx
  next.config.js
  package.json
  pages/404.tsx
  pages/[...slug].tsx
  pages/_app.tsx
  pages/index.tsx
  tailwind.config.js
  yarn.lock
Labels: size/l

#31 SUL23-38 | @jdwjdwjdw | Build "Event" content display
  components/nodes/node-stanford-event.tsx
  components/paragraphs/stanford-entity.tsx
  components/paragraphs/stanford-lists.tsx
Labels: size/s

#37 SUL23-60 Style the interior page header and footer
  components/header.tsx
  components/layouts/main-content-layout.tsx
  components/layouts/page-layout.tsx
  components/menu/main-menu.tsx
  components/nodes/node-stanford-event.tsx
  components/nodes/node-stanford-news.tsx
  components/nodes/node-stanford-page.tsx
  components/patterns/global-footer.tsx
  components/patterns/identity-bar.tsx
  components/patterns/library-footer.tsx
  components/patterns/lockup.tsx
  components/preview-alert.tsx
  components/simple/conditional.tsx
  components/simple/icons/FacebookIcon.tsx
  components/simple/icons/InstagramIcon.tsx
  components/simple/icons/LinkedInIcon.tsx
  components/simple/icons/TwitterIcon.tsx
  components/simple/icons/YoutubeIcon.tsx
  context/state.tsx
  lib/fetch-paragraphs.tsx
  pages/[...slug].tsx
  pages/api/menu.tsx
  public/footer-sprinkles.png
  public/interior-header-sprinkles.png
  tailwind.config.js
  types/drupal.d.ts
Labels: size/s

#38 Refactored lists and teaser paragraphs to use axios instead of swr
  .env.example
  CHANGELOG.md
  README.md
  composer.json
  src/components/nodes/node-stanford-news.tsx
  src/components/paragraphs/stanford-entity.tsx
  src/components/paragraphs/stanford-lists.tsx
  src/components/simple/oembed.tsx
  src/pages/[...slug].tsx
  src/pages/api/views/[...slug].tsx
Labels: size/s
