Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2023-03, with the labels that each got.

#51 SUL23-66 Implement LibCal & LibGuides on people content
  .env.example
  package.json
  src/components/nodes/node-stanford-person.tsx
  src/components/paragraphs/stanford-image-gallery.tsx
  src/components/simple/modal.tsx
  src/lib/clean-node.tsx
  src/lib/fetch-paragraphs.tsx
  src/pages/api/node/[...slug].tsx
  src/types/drupal.d.ts
  tailwind.config.js
  yarn.lock
Labels: size/xl

#54 SUL23-128-three-card-link-styles
  src/components/paragraphs/stanford-card.tsx
  src/components/patterns/card.tsx
  src/components/simple/link.tsx
  src/types/drupal.d.ts
Labels: size/xs

#61 Provide authentication for page previews
  .github/workflows/build_lint.yml
  .github/workflows/update-dev-test-branches.yml
  app/(public)/[...slug]/layout.tsx
  app/(public)/[...slug]/page.tsx
  app/(public)/components/node/stanford-event-series/page-display.tsx
  app/(public)/components/node/stanford-event/page-display.tsx
  app/(public)/components/node/stanford-news/page-display.tsx
  app/(public)/components/node/stanford-page/home-page/page-display.tsx
  app/(public)/components/node/stanford-page/page-display.tsx
  app/(public)/components/node/stanford-person/page-display.tsx
  app/(public)/components/node/stanford-publication/page-display.tsx
  app/(public)/components/node/sul-library/page-display.tsx
  app/(public)/components/paragraph/index.tsx
  app/(public)/error.tsx
  app/(public)/layout.tsx
  app/(public)/lib/fetch-components.tsx
  app/(public)/lib/format-date.tsx
  app/(public)/page.tsx
  yarn.lock
Labels: size/m

#60 SUL23-135 | @jdwjdwjdw | Add global typography styles
  app/(public)/components/node/stanford-course/card.tsx
  app/(public)/components/node/stanford-event-series/card.tsx
  app/(public)/components/node/stanford-event/card.tsx
  app/(public)/components/node/stanford-news/card.tsx
  app/(public)/components/node/stanford-page/card.tsx
  app/(public)/components/node/stanford-person/horizontal-card.tsx
  app/(public)/components/node/stanford-person/vertical-card.tsx
  app/(public)/components/node/stanford-publication/card.tsx
  app/(public)/components/node/sul-library/library-header.tsx
  app/(public)/components/paragraph/stanford-entity.tsx
  app/(public)/components/paragraph/stanford-image-gallery.tsx
  app/(public)/components/paragraph/stanford-lists.tsx
  app/(public)/components/paragraph/stanford-media-caption.tsx
  app/(public)/components/paragraph/sul-collection.tsx
  app/(public)/components/paragraph/sul-featured-collection.tsx
  app/(public)/components/patterns/card.tsx
  app/(public)/lib/format-html.tsx
  app/(public)/styles/tailwind/plugins/base/base.js
  app/(public)/styles/tailwind/plugins/components/simple/sul-button.js
  tailwind.config.js
Labels: size/s

#56 SUL23-118 | @jdwjdwjdw | style Contact Card Paragraph
  app/(public)/components/paragraph/index.tsx
  app/(public)/components/paragraph/sul-contact-card.tsx
  app/(public)/lib/hooks/useLibraryHours.tsx
Labels: size/s

#65 SUL23-118 Refactor stub to rebuild the contact card
  app/(public)/components/paragraph/index.tsx
  app/(public)/components/paragraph/sul-contact-card.tsx
  app/(public)/components/paragraph/sul-contact-card/index.tsx
  app/(public)/components/paragraph/sul-contact-card/manual-fields-card.tsx
  app/(public)/components/paragraph/sul-contact-card/node-reference-card.tsx
Labels: size/s

#67 SUL23-000 | @jdwjdwjdw | Fixup for React Select
  app/(public)/components/node/sul-library/library-hours.tsx
  app/(public)/components/views/study-places.tsx
Labels: size/xs

#68 SUL23-193 Style events cards to match designs
  app/(public)/components/node/stanford-event/card.tsx
  app/(public)/components/node/stanford-event/list-item.tsx
  app/(public)/lib/format-html.tsx
Labels: size/s

#69 Display and style the global message at the top of the site
  app/(admin)/admin/paragraph/[id]/page.tsx
  app/(public)/[...slug]/metadata.tsx
  app/(public)/[...slug]/page.tsx
  app/(public)/components/layout/header.tsx
  app/(public)/components/node/index.tsx
  app/(public)/components/node/node-card.tsx
  app/(public)/components/node/node-list-display.tsx
  app/(public)/components/node/stanford-event-series/page-display.tsx
  app/(public)/components/node/stanford-event/card.tsx
  app/(public)/components/node/stanford-event/page-display.tsx
  app/(public)/components/node/stanford-news/card.tsx
  app/(public)/components/node/stanford-page/home-page/page-display.tsx
  app/(public)/components/node/stanford-page/page-display.tsx
  app/(public)/components/paragraph/index.tsx
  app/(public)/components/paragraph/stanford-entity.tsx
  app/(public)/components/paragraph/stanford-lists.tsx
  app/(public)/components/patterns/global-message.tsx
  app/(public)/components/patterns/modal.tsx
  app/(public)/layout.tsx
  app/(public)/lib/drupal/deserialize.tsx
  app/(public)/lib/drupal/drupal.d.ts
  app/(public)/lib/drupal/get-access-token.tsx
  app/(public)/lib/drupal/get-menu.tsx
  app/(public)/lib/drupal/get-paths.tsx
  app/(public)/lib/drupal/get-resource.tsx
  app/(public)/lib/drupal/get-search-index.tsx
  app/(public)/lib/drupal/get-view.tsx
  app/(public)/lib/drupal/translate-path.tsx
  app/(public)/lib/drupal/utils.tsx
  app/(public)/lib/fetch-components.tsx
  app/(public)/lib/hooks/useLibraryHours.tsx
  package.json
  yarn.lock
Labels: size/s

#70 SUL23 115 feedback
  app/(public)/components/paragraph/rows/one-column.tsx
  app/(public)/components/paragraph/stanford-card.tsx
  app/(public)/components/patterns/card-sprinkles.tsx
  app/(public)/components/patterns/card.tsx
  app/(public)/components/patterns/horizontal-card.tsx
Labels: size/s

#62 SUL23-115 - Horizontal card option
  app/(public)/components/paragraph/rows/one-column.tsx
  app/(public)/components/paragraph/stanford-card.tsx
  app/(public)/components/patterns/card-sprinkles.tsx
  app/(public)/components/patterns/card.tsx
  app/(public)/components/patterns/horizontal-card.tsx
  app/(public)/lib/drupal/drupal.d.ts
  public/sprinkles-horizontal-card.png
  public/sprinkles/sprinkles-bottom-left-horizontal-card.png
  public/sprinkles/sprinkles-bottom-right-horizontal-card.png
  public/sprinkles/sprinkles-top-left-horizontal-card.png
  public/sprinkles/sprinkles-top-right-horizontal-card.png
  tailwind.config.js
Labels: size/s
