Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2023-11, with the labels that each got.

#86 Rewrite image urls to exclude unwanted params
  components/patterns/elements/select-list.tsx
  lib/hooks/useIsCentered.tsx
  next.config.js
  package.json
  public/no-image.png
  yarn.lock
Labels: size/m

#87 Use nextJS draft mode instead of preview
  .env.example
  .github/workflows/build_lint.yml
  app/(public)/[...slug]/page.tsx
  app/(public)/layout.tsx
  app/api/draft/disable/route.tsx
  app/api/draft/route.tsx
  app/layout.tsx
  components/editori11y.tsx
  components/layout/library-footer.tsx
  components/node/stanford-page/page-display.tsx
  components/paragraph/index.tsx
  components/patterns/unpublished-banner.tsx
  lib/drupal/deserialize.tsx
  lib/drupal/get-access-token.tsx
  lib/drupal/get-menu.tsx
  lib/drupal/get-paths.tsx
  lib/drupal/get-resource.tsx
  lib/drupal/get-search-index.tsx
  lib/drupal/get-view.tsx
  lib/drupal/is-draft-mode.tsx
  lib/drupal/sync-drupal-preview-path.tsx
  lib/drupal/translate-path.tsx
  lib/drupal/utils.tsx
  lib/fetch-components.tsx
  src/pages/api/preview.tsx
Labels: size/s

#90 Fixup: Footer link relative path.
  components/layout/library-footer.tsx
Labels: size/xs

#91 NoJira: On demand revalidation only and no caching requests.
  app/(public)/[...slug]/page.tsx
Labels: size/xs
