Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2023-01, with the labels that each got.

#40 SUL23-37, SUL23-44, SUL23-51 | @jdwjdwjdw | Build "Course" content display
  src/components/nodes/node-stanford-course.tsx
Labels: size/s

#43 SUL23-61 Build and style home page banner search
  public/home-banner-sprinkles.png
  src/components/layouts/main-content-layout.tsx
  src/components/menu/main-menu.tsx
  src/components/nodes/index.tsx
  src/components/nodes/node-stanford-page.tsx
  src/components/nodes/node-sul-library.tsx
  src/components/paragraphs/index.tsx
  src/components/paragraphs/row.tsx
  src/components/paragraphs/stanford-banner.tsx
  src/components/paragraphs/stanford-card.tsx
  src/components/patterns/card.tsx
  src/components/search/search-works.tsx
  src/lib/hooks/useLibraryHours.tsx
  src/lib/hooks/useNode.tsx
  src/lib/hooks/useNodeList.tsx
  src/pages/api/node/[...slug].tsx
  tailwind.config.js
  yarn.lock
Labels: size/m

#46 SUL-000 | @jdwjdwjdw | Fix up homepage banner select width and text being cut off
  src/components/nodes/node-stanford-page.tsx
Labels: size/xs

#45 SUL23-113 Fix link/button styles and scaffold the background behaviors
  next.config.js
  public/robots.txt
  src/components/nodes/node-stanford-event.tsx
  src/components/paragraphs/stanford-card.tsx
  src/components/paragraphs/stanford-entity.tsx
  src/components/patterns/card.tsx
  src/components/simple/link.tsx
  src/lib/format-html.tsx
  src/types/drupal.d.ts
Labels: size/s

#41 SUL23-41, SUL23-48, SUL23-55 | @jdwjdwjdw | build person node, list, and card
  src/components/nodes/node-stanford-person.tsx
  src/components/paragraphs/stanford-lists.tsx
  src/types/drupal.d.ts
Labels: size/s
