Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2023-02, with the labels that each got.

#44 SUL23-70 | @jdwjdwjdw | Build and style the library branch pages
  src/components/nodes/node-sul-library.tsx
  src/lib/hooks/useLibraryHours.tsx
Labels: size/s

#48 SUL23-71 Stubbed out study place filtering list
  package.json
  src/components/nodes/node-sul-study-place.tsx
  src/components/paragraphs/stanford-lists.tsx
  src/components/views/study-places.tsx
  yarn.lock
Labels: size/m

#47 SUL23-42 | @jdwjdwjdw | Build Publication content display in NextJS
  src/components/nodes/node-stanford-publication.tsx
  src/components/patterns/card.tsx
Labels: size/s

#50 Add sizeMe, add ternary conditional
  package-lock.json
  package.json
  src/components/nodes/node-stanford-person.tsx
  yarn.lock
Labels: size/xl

#49 SUL23-126 | @jdwjdwjdw | Adjust Person card display
  package-lock.json
  package.json
  src/components/nodes/node-stanford-person.tsx
  yarn.lock
Labels: size/xl

#52 SUL23-125 | @jdwjdwjdw | Update branch content type to include center functionality
  src/components/nodes/node-sul-library.tsx
Labels: size/xs
