Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2024-10, with the labels that each got.

#219 Release 1.4.1
  app/api/revalidate/route.tsx
  package.json
  src/components/layout/global-message.tsx
  src/components/node/stanford-news/page-display.tsx
  src/components/paragraph/stanford-lists.tsx
  src/components/paragraph/sul-collection.tsx
  src/components/paragraph/sul-featured-collection.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fetcher.tsx
  src/lib/gql/fragments-fields.drupal.gql
  yarn.lock
Labels: size/m

#224 SUL23-650 | add Reservation not required to places to study with no reservation button
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#226 SUL23-647 | add margin bottom to Dek text
  src/components/node/stanford-news/page-display.tsx
Labels: size/xs

#227 SUL23-596: Displays for ascending and descending events
  app/sitemap.tsx
  package.json
  src/components/paragraph/stanford-lists.tsx
  src/components/views/view.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/view-queries.drupal.gql
  yarn.lock
Labels: size/m

#225 SUL23-649 | remove underline from checked/selected state
  src/components/patterns/toggle-option.tsx
Labels: size/xs

#228 SUL23-652 | adjust select list to fit text
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#222 SUL23-638 | scaffold on this page and related content block
  app/[...slug]/page.tsx
  app/layout.tsx
  src/components/paragraph/stanford-wysiwyg.tsx
  src/components/patterns/accordion.tsx
  src/components/patterns/elements/select-list.tsx
  src/components/patterns/headingList.tsx
  src/components/patterns/on-the-page.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments-nodes.drupal.gql
  src/lib/hooks/useAccordion.tsx
Labels: size/s

#230 SUL23-655 Refactor tabs to eliminate html validation errors
  app/[...slug]/page.tsx
  src/components/node/stanford-page/page-display.tsx
  src/components/paragraph/stanford-entity.tsx
  src/components/paragraph/sul-collection.tsx
  src/components/paragraph/sul-contact-card/node-reference-card.tsx
  src/components/patterns/elements/tabs.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fetcher.tsx
  src/lib/gql/route-query.drupal.gql
Labels: size/s

#231 SUL23-650 | update font to match mocks
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#233 SUL23-652 | adjust filter width and margin bottom
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#235 SUL23-662 | adjust news filters
  src/components/node/stanford-news/card.tsx
  src/components/patterns/elements/select-list.tsx
  src/components/views/stanford-news/filtering-news-card-view.client.tsx
Labels: size/s

#234 SUL23-662 Created news filtering view display
  package.json
  src/components/node/stanford-news/card.tsx
  src/components/paragraph/stanford-lists.tsx
  src/components/patterns/elements/select-list.tsx
  src/components/patterns/toggle-option.tsx
  src/components/views/stanford-news/filtering-news-card-view.client.tsx
  src/components/views/stanford-news/filtering-news-card-view.tsx
  src/components/views/stanford-news/news-list-view.tsx
  src/components/views/view.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/entity-queries.drupal.gql
  src/lib/gql/view-queries.drupal.gql
  src/lib/hooks/useServerAction.tsx
  yarn.lock
Labels: size/s

#236 SUL23-638 | update file and heading naming and update intersection observer config
  app/[...slug]/page.tsx
  src/components/patterns/headingList.tsx
  src/components/patterns/on-this-page.tsx
Labels: size/xs

#237 SUL23-665 | resolve overlapping card image for certain breakpoints
  src/components/paragraph/stanford-card.tsx
  src/components/patterns/horizontal-card.tsx
Labels: size/xs

#238 SUL23-654 | swap out article for div and add article wrapper to main content
  app/[...slug]/page.tsx
  src/components/node/stanford-page/page-display.tsx
Labels: size/s

#239 SUL23-664 | update to Stanford Libraries for meta data title
  app/[...slug]/metadata.tsx
Labels: size/xs

#240 SUL23-666 | add typography to match places to study
  src/components/views/stanford-news/filtering-news-card-view.client.tsx
Labels: size/s

#242 SUL23-668 | change last 12 months to last 90 days
  src/components/views/stanford-news/filtering-news-card-view.client.tsx
Labels: size/xs

#243 Pure css to hide/show clear button on text fields
  src/components/views/stanford-news/filtering-news-card-view.client.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/xs
