Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2024-08, with the labels that each got.

#191 SUL23-578: fixup to the margin-bottom and casing
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/lib/format-date.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/hooks/useTodayLibraryHours.tsx
Labels: size/xs

#188 SUL23-551: sentence case for branches and places to study
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#189 SUL23-482: set Todays hours title to h2
  src/components/node/stanford-page/home-page/today-hours.tsx
Labels: size/xs

#192 SUL23-577: fixed button height. removed include not used
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-today-hours-table.tsx
Labels: size/xs

#193 SUL23-587: updates to the people table
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/xs

#195 SUL23-598: fixup up hover on branch name
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#196 SUL23-574: setting exact height
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/xs

#197 SUL23-580 SUL23-538: Added in the at to the time string
  src/lib/hooks/useTodayLibraryHours.tsx
Labels: size/xs

#198 SUL23-585: Adding Donate now button to header
  src/components/layout/header.tsx
  src/components/menu/main-menu.tsx
Labels: size/xs

#201 SUL23-585: Back to digital red
  src/components/layout/header.tsx
  src/components/menu/main-menu.tsx
Labels: size/xs

#202 SUL23-600 show closing minutes if they are not 00
  src/lib/hooks/useTodayLibraryHours.tsx
Labels: size/xs

#203 SUL-23-570: adding Hours this week for default
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs

#205 SUL23-603: removed padding-left on branch name
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs

#206 SUL23-604: tweaking the toggle spacing
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#207 SUL23-608: changed the padding-left when the browser size is smaller
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs

#199 SUL23-573: tightening up spacing
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/styles/globals.css
Labels: size/s

#204 SUL23-605: fine tuning the sul people page.
  package.json
  src/components/patterns/elements/telephone-link.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  yarn.lock
Labels: size/l

#208 SUL23-601: changed when focused to not be red with red underline
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/xs

#209 SUL23-609: fix to text in hours card on homepage
  src/components/node/stanford-page/home-page/today-hours.tsx
Labels: size/xs

#210 Sul23 611 toggles
  package.json
  src/components/patterns/toggle-option.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  yarn.lock
Labels: size/s
