Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2024-07, with the labels that each got.

#161 SUL23-524: fixup to buttons
  src/components/views/sul-people/libcal.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#160 SUL23-518: Open/Closed on one line for sm mobile only
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs

#164 Release 1.3.0
  .env.example
  .eslintrc.json
  .githooks/pre-commit
  .github/workflows/build_lint.yml
  .github/workflows/label.yml
  .github/workflows/release.yml
  .github/workflows/update-dev-test-branches.yml
  .gitpod.yml
  .prettierrc
  app/[...slug]/page.tsx
  app/preview/layout.tsx
  codegen.ts
  package.json
  src/components/node/stanford-page/home-page/home-page-banner.tsx
  src/components/node/stanford-page/home-page/today-hours.tsx
  src/components/paragraph/index.tsx
  src/components/paragraph/stanford-lists.tsx
  src/components/patterns/elements/address.tsx
  src/components/patterns/elements/editor-alert-banner.tsx
  src/components/patterns/elements/select-list.tsx
  src/components/patterns/unpublished-banner.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-table.tsx
  src/components/views/sul-people/libcal.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-today-hours-table.tsx
  src/components/views/view.tsx
  src/lib/drupal/get-access-token.tsx
  src/lib/drupal/get-search-index.tsx
  src/lib/drupal/utils.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fetcher.tsx
  src/lib/gql/fragments.drupal.gql
  src/lib/gql/view-queries.drupal.gql
  src/lib/hooks/useLibraryHours.tsx
  src/lib/hooks/useTodayLibraryHours.tsx
  src/lib/libguides.tsx
  src/styles/globals.css
  tailwind.config.js
  vercel.json
  yarn.lock
Labels: size/xl

#166 SUL23-540: Updated robots.txt to disallow /all/
  public/robots.txt
Labels: size/xs

#165 Better automated tests & Gitpod by building a cloned site
  .github/workflows/build_lint.yml
  .gitpod.yml
Labels: size/s

#168 Remove node cache to improve cache invalidation for config pages
  app/api/revalidate/route.tsx
  src/components/menu/main-menu.tsx
  src/components/menu/secondary-menu.tsx
  src/lib/drupal/get-cache.tsx
  src/lib/drupal/utils.tsx
  src/lib/gql/fetcher.tsx
  src/lib/hooks/useActiveTrail.tsx
  src/lib/libguides.tsx
Labels: size/s

#169 SUL23-515 SUL23-541: Colors, fonts, word fixes to the toggles.
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#156 Keyword search filter stubbed out
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/s

#170 SUL23-525: Updates to the display for Med breakpoint on Branches and Centers
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/styles/globals.css
Labels: size/xs

#163 SUL23-438: Moved the location link and changed to Open or Closed until
  .yarn/releases/yarn-4.1.1.cjs
  .yarn/releases/yarn-4.3.1.cjs
  .yarnrc.yml
  app/api/library-hours/route.tsx
  package.json
  src/components/node/stanford-page/home-page/today-hours.tsx
  src/components/node/sul-library/library-hours.tsx
  src/components/node/sul-library/library-select-options.tsx
  src/components/patterns/elements/email-link.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/lib/gql/fetcher.tsx
  src/lib/hooks/useTodayLibraryHours.tsx
  tsconfig.json
  yarn.lock
Labels: size/l

#176 SUL23-479: added space
  src/components/patterns/lockup.tsx
Labels: size/xs

#172 SUL23-549: places to study alignment
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-today-hours-table.tsx
  src/styles/globals.css
Labels: size/xs

#175 SUL23-570: adding the corrected times to the places to study table
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/s

#171 SUL23-550: Move the condition so the td element remained even when empty
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/xs

#173 SUL23-548 SUL23-553 SUL23-554 SUL23-555 SUL23-556 SUL23-547
  src/components/patterns/elements/select-list.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#177 SUL23-557: adding aria-hidden and tabindex for a11y to photos on tabular data tables
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#178 Adjust how library hours data is cached to reduce cache writes/reads
  app/api/library-hours/route.tsx
Labels: size/s

#180 SUL23-503: search label font size
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/xs

#179 SUL23-579: changed address to size 16
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs

#184 SUL23-580: nav fixup
  src/components/menu/main-menu.tsx
Labels: size/xs

#186 SUL23-556: normal font and leading
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#185 SUL23-503 Add text reset button and no results display
  src/components/views/sul-people/sul-people-table-view.tsx
Labels: size/s

#183 SUL23-577 SUL23-586: buttons and vertical centering on tables
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/libcal.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#182 SUL23-576 SUL23-575 SUL23-574: fixed height of toggle and filters
  src/components/patterns/elements/select-list.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#187 SUL23-591: added the th row=scope for a11y
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs
