Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2024-06, with the labels that each got.

#141 Sul23 434
  package.json
  src/components/paragraph/stanford-lists.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/view.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/view-queries.drupal.gql
  yarn.lock
Labels: size/xl

#132 Release 1.2.0
  .github/pull_request_template.md
  app/page.tsx
  app/search/search.tsx
  package.json
  src/components/node/stanford-course/card.tsx
  src/components/node/stanford-event/card.tsx
  src/components/node/stanford-event/page-display.tsx
  src/components/node/stanford-news/card.tsx
  src/components/node/stanford-news/page-display.tsx
  src/components/node/stanford-page/home-page/home-page-banner.tsx
  src/components/node/stanford-page/home-page/today-hours.tsx
  src/components/node/stanford-page/page-display.tsx
  src/components/node/stanford-person/horizontal-card.tsx
  src/components/node/stanford-person/libcal.tsx
  src/components/node/stanford-person/list-item.tsx
  src/components/node/stanford-person/page-display.tsx
  src/components/node/stanford-person/vertical-card.tsx
  src/components/node/sul-library/library-additional-hours.tsx
  src/components/node/sul-library/library-header.tsx
  src/components/node/sul-library/library-hours.tsx
  src/components/node/sul-library/page-display.tsx
  src/components/node/sul-study-place/card.tsx
  src/components/node/sul-study-place/study-place-features.tsx
  src/components/node/sul-study-place/study-place-today-hours.tsx
  src/components/paragraph/stanford-entity.tsx
  src/components/paragraph/stanford-lists.tsx
  src/components/paragraph/sul-collection.tsx
  src/components/paragraph/sul-contact-card/manual-fields-card.tsx
  src/components/paragraph/sul-contact-card/node-reference-card-hours.tsx
  src/components/paragraph/sul-contact-card/node-reference-card.tsx
  src/components/paragraph/sul-featured-collection.tsx
  src/components/patterns/banner.tsx
  src/components/patterns/card.tsx
  src/components/patterns/elements/select-list.tsx
  src/components/patterns/horizontal-card.tsx
  src/components/patterns/link.tsx
  src/components/patterns/modals/interception-modal.tsx
  src/components/patterns/modals/modal.tsx
  src/components/search/search-form.tsx
  src/components/views/card-list.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/study-place-filtering.tsx
  src/components/views/view.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/view-queries.drupal.gql
  src/styles/tailwind/plugins/base/base.js
  yarn.lock
Labels: size/xl

#140 SUL23-431: version 2 of date padding
  app/page.tsx
Labels: size/xs

#143 Release 1.2.1
  app/page.tsx
Labels: size/xs

#144 Improve person table logic
  package.json
  src/components/views/sul-people/sul-people-table-view.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments.drupal.gql
  src/styles/globals.css
  yarn.lock
Labels: size/s

#148 SUL23-489: Places to study table.
  .github/workflows/build_lint.yml
  .github/workflows/label.yml
  .github/workflows/update-dev-test-branches.yml
  package.json
  src/components/paragraph/stanford-lists.tsx
  src/components/patterns/elements/select-list.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-today-hours-table.tsx
  src/components/views/view.tsx
  src/lib/hooks/useLibraryHours.tsx
  src/styles/globals.css
  yarn.lock
Labels: size/m

#147 Feature/SUL23-441: People grid
  package.json
  src/components/paragraph/stanford-lists.tsx
  src/components/views/sul-people/libcal.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/components/views/view.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments.drupal.gql
  src/styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: size/m

#149 SUL23-490: Set up front end scaffolding for Branch Locations table list
  src/components/paragraph/stanford-lists.tsx
  src/components/patterns/elements/address.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/components/views/sul-study-place/filtering-table/study-place-today-hours-table.tsx
  src/components/views/view.tsx
  src/lib/gql/__generated__/drupal.d.ts
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments.drupal.gql
  src/lib/gql/view-queries.drupal.gql
Labels: size/s

#150 SUL23-438: Added location link to list of branches on the homepage
  src/components/node/stanford-page/home-page/home-page-banner.tsx
  src/components/node/stanford-page/home-page/today-hours.tsx
Labels: size/s

#155 Mapped NodeStanfordPerson correctly for table view
  src/components/views/view.tsx
Labels: size/xs

#157 SUL23-516: added col headings back to the table
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs

#159 SUL23-521 & SUL23-522: Fixed the sm and med breakpoints
  src/components/views/sul-people/sul-people-table-view.tsx
  src/styles/globals.css
Labels: size/xs

#151 SUL23-506: Fix to toggle outline on study places
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#152 SUL23-508: fixed bgcolor on features for md and down
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
Labels: size/xs

#158 SUL23-520: Added the pin and removed the US from address
  src/components/patterns/elements/address.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs
