Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2025-08, with the labels that each got.

#311 SUL23-807 | add aria-label to jumpto links when multiple link text exists
  src/components/patterns/headingList.tsx
Labels: size/s, size/xs

#317 SUL23-828 | remove rosette id
  .github/workflows/build_lint.yml
  src/components/patterns/icons/RosetteIcon.tsx
Labels: size/xs

#321 SUL23-833 | update padding right to modular spacer for branch center list table
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
Labels: size/xs

#322 SUL23-837: Added research and person types to person search API results
  app/api/people/search/route.tsx
  src/lib/gql/__generated__/drupal.d.tsx
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/view-queries.drupal.gql
Labels: size/xs

#324 SUL23-841 | update library hours alert to conditionally display
  src/components/paragraph/sul-location-hour/sul-location-hour.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
Labels: size/xs

#320 Update github actions for Drupal 11
  .github/workflows/build_lint.yml
  .github/workflows/release.yml
  package.json
  yarn.lock
Labels: size/l

#319 SUL23-816 | pull over stats card and layout components from cardinalsites
  app/layout.tsx
  package.json
  src/components/paragraph/index.tsx
  src/components/paragraph/rows/one-column.tsx
  src/components/paragraph/rows/rows.tsx
  src/components/paragraph/rows/three-column.tsx
  src/components/paragraph/rows/two-column.tsx
  src/components/paragraph/stanford-stat-card/stat-card-paragraph.tsx
  src/components/patterns/count-up.tsx
  src/components/patterns/image-card.tsx
  src/components/patterns/reverse-visual-order.tsx
  src/lib/drupal/drupal.d.ts
  src/lib/gql/__generated__/drupal.d.tsx
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments-fields.drupal.gql
  src/lib/gql/fragments-paragraphs.drupal.gql
  src/styles/globals.css
  src/styles/typography/fonts.tsx
  tailwind.config.js
  yarn.lock
Labels: size/s, size/m
