Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2025-01, with the labels that each got.

#254 SUL23-693 | fix html validation issue for social share
  src/components/node/stanford-news/page-display.tsx
Labels: size/xs

#253 SUL23-698 | fixup about us menu item display
  src/components/menu/fallback-main-menu.tsx
  src/components/menu/main-menu.tsx
Labels: size/xs

#251 SUL23-690 | build out and configure accordion component
  src/components/node/stanford-publication/page-display.tsx
  src/components/paragraph/index.tsx
  src/components/paragraph/stanford-accordion.tsx
  src/components/patterns/elements/accordion.tsx
  src/components/patterns/elements/expand-collapse-all.tsx
  src/components/patterns/on-this-page.tsx
  src/components/patterns/sul-accordion.tsx
  src/lib/drupal/drupal.d.ts
  src/lib/gql/__generated__/drupal.d.tsx
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments-paragraphs.drupal.gql
Labels: size/xl

#255 SUL23-691 | add id to branch page h1 to fix arialabelledby html validation error
  src/components/node/sul-library/library-header.tsx
Labels: size/xs

#258 SUL23-707 | add caption option to card
  src/components/paragraph/stanford-card.tsx
  src/components/patterns/card.tsx
Labels: size/xs

#256 SUL23-700: lockup options
  src/components/images/stanford-wordmark.tsx
  src/components/layout/header.tsx
  src/components/patterns/elements/lockup/lockup-a.tsx
  src/components/patterns/elements/lockup/lockup-b.tsx
  src/components/patterns/elements/lockup/lockup-d.tsx
  src/components/patterns/elements/lockup/lockup-e.tsx
  src/components/patterns/elements/lockup/lockup-h.tsx
  src/components/patterns/elements/lockup/lockup-i.tsx
  src/components/patterns/elements/lockup/lockup-logo.tsx
  src/components/patterns/elements/lockup/lockup-m.tsx
  src/components/patterns/elements/lockup/lockup-o.tsx
  src/components/patterns/elements/lockup/lockup-p.tsx
  src/components/patterns/elements/lockup/lockup-r.tsx
  src/components/patterns/elements/lockup/lockup-s.tsx
  src/components/patterns/elements/lockup/lockup-t.tsx
  src/components/patterns/elements/lockup/lockup.tsx
  src/lib/gql/fetcher.tsx
Labels: size/m

#259 SUL23 701
  app/page.tsx
  app/search/page.tsx
  app/search/search.tsx
  next-env.d.ts
  package.json
  src/components/node/stanford-event/card.tsx
  src/components/node/stanford-page/card.tsx
  src/components/paragraph/index.tsx
  src/components/paragraph/stanford-lists.tsx
  src/components/paragraph/sul-home-banner/sul-home-banner.client.tsx
  src/components/paragraph/sul-home-banner/sul-home-banner.tsx
  src/components/paragraph/sul-home-image/sul-home-image.tsx
  src/components/paragraph/sul-location-hour/sul-location-hour.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
  src/components/patterns/card.tsx
  src/components/patterns/icons/MoonStarsIcon.tsx
  src/components/patterns/load-more-list.tsx
  src/components/search/search-page.tsx
  src/components/views/search-search/search-search-view.tsx
  src/components/views/view.tsx
  src/lib/drupal/drupal.d.ts
  src/lib/gql/__generated__/drupal.d.tsx
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments-nodes.drupal.gql
  src/lib/gql/fragments-paragraphs.drupal.gql
  src/lib/gql/gql-views.tsx
  src/lib/gql/view-queries.drupal.gql
  src/lib/text-tools.tsx
  tailwind.config.js
  yarn.lock
Labels: size/xl

#260 SUL23-701 SUL23-703 | Adjust homepage hero banner, library location card, and default card styles
  app/page.tsx
  src/components/node/stanford-page/page-display.tsx
  src/components/node/stanford-publication/page-display.tsx
  src/components/node/sul-library/page-display.tsx
  src/components/paragraph/rows/one-column.tsx
  src/components/paragraph/rows/rows.tsx
  src/components/paragraph/rows/three-column.tsx
  src/components/paragraph/rows/two-column.tsx
  src/components/paragraph/sul-home-banner/sul-home-banner.client.tsx
  src/components/paragraph/sul-home-banner/sul-home-banner.tsx
  src/components/paragraph/sul-home-image/sul-home-image.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
  src/components/patterns/card.tsx
  src/lib/gql/__generated__/drupal.d.tsx
Labels: size/xl

#261 SUL23-707 | update image caption source
  src/components/paragraph/index.tsx
  src/components/paragraph/stanford-card.tsx
  src/components/patterns/card.tsx
  src/lib/gql/__generated__/drupal.d.tsx
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments-paragraphs.drupal.gql
Labels: size/xs

#262 SUL23-701 | add homepage h1
  app/page.tsx
Labels: size/xs

#263 Remove duplicate link on list paragraph
  package.json
  src/components/paragraph/stanford-lists.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
  src/lib/gql/fetcher.tsx
  yarn.lock
Labels: size/s

#264 SUL23-702 SUL23-704 SUL23-707 | Implement QA feedback
  src/components/paragraph/rows/one-column.tsx
  src/components/paragraph/rows/rows.tsx
  src/components/paragraph/rows/three-column.tsx
  src/components/paragraph/rows/two-column.tsx
  src/components/paragraph/sul-home-banner/sul-home-banner.client.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
Labels: size/xs

#257 nojira | update readme to include PR workflow
  README.md
Labels: size/s

#265 SUL23-702 SUL23-704 | adjust rows spacing and sync card font-size
  src/components/paragraph/rows/rows.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
Labels: size/xs

#266 SUL23-704 SUL23-728 | adjust horizontal card spacing for lg, adjust header and update lockup in footer
  src/components/layout/header.tsx
  src/components/layout/library-footer.tsx
  src/components/paragraph/stanford-card.tsx
  src/components/paragraph/sul-home-image/sul-home-image.tsx
  src/components/patterns/elements/lockup/lockup-logo.tsx
  src/components/patterns/elements/lockup/lockup.tsx
Labels: size/xs
