Repository SU-SWS/sulgryphon-nextjs, pull requests merged in 2025-05, with the labels that each got.

#293 SUL23-773 SUL23-774 | resolve media image center bug and site improve overflow hidden issue
  src/components/patterns/card.tsx
  src/lib/format-html.tsx
Labels: size/xs

#290 SUL23-751 | switch to decanter recommended line heights
  app/[...slug]/page.tsx
  src/components/layout/header.tsx
  src/components/layout/library-footer.tsx
  src/components/node/stanford-course/card.tsx
  src/components/node/stanford-event-series/page-display.tsx
  src/components/node/stanford-event/card.tsx
  src/components/node/stanford-event/page-display.tsx
  src/components/node/stanford-news/card.tsx
  src/components/node/stanford-news/list-item.tsx
  src/components/node/stanford-news/page-display.tsx
  src/components/node/stanford-page/card.tsx
  src/components/node/stanford-person/vertical-card.tsx
  src/components/node/sul-library/card.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
  src/components/patterns/card.tsx
  src/components/patterns/headingList.tsx
  src/components/patterns/horizontal-card.tsx
  src/components/patterns/toggle-option.tsx
  src/components/views/stanford-news/filtering-news-card-view.client.tsx
  src/components/views/sul-people/libcal.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/styles/tailwind/plugins/base/base.js
Labels: size/s

#289 SUL23-767 | rework horizontal card
  public/card-rosette.png
  src/components/paragraph/index.tsx
  src/components/paragraph/stanford-card.tsx
  src/components/patterns/horizontal-card.tsx
  src/components/patterns/link.tsx
  src/lib/drupal/drupal.d.ts
  src/lib/format-html.tsx
  src/lib/gql/__generated__/drupal.d.tsx
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments-paragraphs.drupal.gql
Labels: size/s

#295 Release 1.6.2
  .yarn/releases/yarn-4.7.0.cjs
  .yarn/releases/yarn-4.9.1.cjs
  .yarnrc.yml
  README.md
  app/[...slug]/page.tsx
  package.json
  public/card-rosette.png
  src/components/layout/global-footer.tsx
  src/components/layout/header.tsx
  src/components/layout/library-footer.tsx
  src/components/menu/main-menu.tsx
  src/components/node/stanford-course/card.tsx
  src/components/node/stanford-event-series/page-display.tsx
  src/components/node/stanford-event/card.tsx
  src/components/node/stanford-event/page-display.tsx
  src/components/node/stanford-news/card.tsx
  src/components/node/stanford-news/list-item.tsx
  src/components/node/stanford-news/page-display.tsx
  src/components/node/stanford-page/card.tsx
  src/components/node/stanford-page/page-display.tsx
  src/components/node/stanford-person/horizontal-card.tsx
  src/components/node/stanford-person/list-item.tsx
  src/components/node/stanford-person/vertical-card.tsx
  src/components/node/sul-library/card.tsx
  src/components/paragraph/index.tsx
  src/components/paragraph/stanford-card.tsx
  src/components/paragraph/stanford-image-gallery.tsx
  src/components/paragraph/stanford-media-caption.tsx
  src/components/paragraph/sul-contact-card/manual-fields-card.tsx
  src/components/paragraph/sul-contact-card/node-reference-card.tsx
  src/components/paragraph/sul-location-hour/sul-location-hours.client.tsx
  src/components/patterns/banner.tsx
  src/components/patterns/card.tsx
  src/components/patterns/elements/select-list.tsx
  src/components/patterns/headingList.tsx
  src/components/patterns/horizontal-card.tsx
  src/components/patterns/internal-header-banner.tsx
  src/components/patterns/link.tsx
  src/components/patterns/toggle-option.tsx
  src/components/views/stanford-news/filtering-news-card-view.client.tsx
  src/components/views/sul-branch-locations/filtering-table/branch-locations-filtering-table.tsx
  src/components/views/sul-people/libcal.tsx
  src/components/views/sul-people/sul-people-table-view.tsx
  src/components/views/sul-study-place/filtering-table/study-place-filtering-table.tsx
  src/components/views/sul-study-place/study-place-filtering.tsx
  src/lib/drupal/drupal.d.ts
  src/lib/format-html.tsx
  src/lib/gql/__generated__/drupal.d.tsx
  src/lib/gql/__generated__/queries.ts
  src/lib/gql/fragments-paragraphs.drupal.gql
  src/styles/tailwind/plugins/base/base.js
  yarn.lock
Labels: size/xl

#291 SUL23-764 | add GA4 event tracking for search options
  src/components/paragraph/sul-home-banner/sul-home-banner.client.tsx
Labels: size/xs

#296 SUL23-769 | fixup conflicting wysiwyg styles
  src/lib/format-html.tsx
  src/styles/tailwind/plugins/base/base.js
Labels: size/xs

#297 SUL23-787 SUL23-788 | resolve wrapping bug at specific breakpoints for main and secondary nav
  src/components/layout/header.tsx
  src/components/menu/main-menu.tsx
  src/components/patterns/elements/lockup/lockup-logo.tsx
  src/components/patterns/elements/lockup/lockup.tsx
Labels: size/xs

#298 SUL23-789 | update rosette display conditional and size, adjust card vertical spacing for horizontal card
  public/card-rosette.png
  src/components/paragraph/index.tsx
  src/components/paragraph/stanford-card.tsx
  src/components/patterns/horizontal-card.tsx
  src/components/patterns/icons/RosetteIcon.tsx
  src/lib/drupal/drupal.d.ts
  src/lib/gql/__generated__/drupal.d.tsx
Labels: size/s

#299 SUL23-789 | add conditional spacing for content
  src/components/patterns/horizontal-card.tsx
Labels: size/xs

#300 SUL23-793 SUL23-794 SUL23-795 | rework page header for basic, person, and news content types
  app/[...slug]/page.tsx
  src/components/node/stanford-news/page-display.tsx
  src/components/node/stanford-person/page-display.tsx
  src/components/patterns/elements/number-link.tsx
  src/components/patterns/internal-header-banner.tsx
Labels: size/s

#301 SUL23-788 | prevent searchworks catalog link from line break
  src/components/layout/header.tsx
Labels: size/xs

#302 SUL23-789 SUL23-793 SUL23-794 | implement qa feedback for horizontal card and page header banner
  app/[...slug]/page.tsx
  app/calendar/[id]/page.tsx
  app/not-found.tsx
  app/search/layout.tsx
  app/study-place/features/[uuid]/page.tsx
  src/components/node/stanford-person/libguide.tsx
  src/components/patterns/horizontal-card.tsx
  src/components/patterns/internal-header-banner.tsx
  src/styles/tailwind/plugins/base/base.js
Labels: size/xs

#305 SUL23-795 | tweak news type font size
  app/[...slug]/page.tsx
Labels: size/xs
